service: serverless-app
provider:
  name: aws
  runtime: nodejs12.x
plugins:
  - serverless-webpack
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

custom:
  webpackConfig: ./webpack.config.js
  includeModules: true
  packager: yarn

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  news:
    handler: handler.news
    events:
      - http:
          path: news
          method: get
